openapi: 3.1.0
info:
  title: Books Mock REST API
  version: 1.0.0
  description: Combined REST API for books and loans.
servers:
  - url: http://localhost:4010
paths:
  /rest/books:
    $ref: "./docs/openapi-books.yaml#/paths/~1rest~1books"
  /rest/books/{id}:
    $ref: "./docs/openapi-books.yaml#/paths/~1rest~1books~1{id}"
  /rest/loans:
    $ref: "./docs/openapi-loans.yaml#/paths/~1rest~1loans"
  /rest/loans/{id}:
    $ref: "./docs/openapi-loans.yaml#/paths/~1rest~1loans~1{id}"
  /rest/loans/{id}/status:
    $ref: "./docs/openapi-loans.yaml#/paths/~1rest~1loans~1{id}~1status"
  /rest/loans/{id}/review:
    $ref: "./docs/openapi-loans.yaml#/paths/~1rest~1loans~1{id}~1review"
